### ISSUE TITLE
[BUG] Cannot log-in to staging (deployed from dev) - hitting 403 error

### ISSUE THREAD

**Issue by anneguo3** [nwplus/admin#142]
Site: https://nw-admin-portal.firebaseapp.com/
<img width="477" alt="Screen Shot 2021-11-26 at 10 21 59 PM" src="https://user-images.githubusercontent.com/40816838/143666378-58964d04-6502-4c7f-aa7e-eb6b1ed6dc6c.png">

**Comment by kevin-zou** [comment]
Fixed - added the URL to Firebase and Google Cloud Console! Also should note that this is actually a production link. We probably won't access the production app through this link _too much_.
